version: '3'

services:
  node-bot-telegram:
    build: . 
    environment:
      - BOT_TOKEN=1677956681:AAH2ZOql73ZX91UoD0xNZRm6XjwSjUQ6D1c
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: botTelegram

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example